import pygame

CREATE_NEW_PLATFORM = pygame.USEREVENT + 1
MOUTH_OPENED = pygame.USEREVENT + 2
MOUTH_CLOSED = pygame.USEREVENT + 3
CREATE_NEW_MONEY = pygame.USEREVENT + 4
CREATE_NEW_ENEMY = pygame.USEREVENT + 5
CREATE_NEW_SHIELD = pygame.USEREVENT + 6